const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const desktop = Boolean(window.magicus);
const splash = $("#splash"); const login = $("#login"); const studio = $("#studio");
const form = $("#access-form"); const username = $("#username"); const accessKey = $("#access-key");
const errorBox = $("#error"); const submit = form.querySelector(".enter"); const rememberAccess = $("#remember-access");
let workspace = { folders: [], projects: [] }; let assets = []; let assetFilter = "all"; let trayFilter = "all"; let trayQuery = ""; let openProjectId = null; let activeFolderId = null; let albumFilter = "all"; let draggedAssetId = null;
let browserBridge = null;
const bridgePath = ".magicus/workspace.json";
const bridgeHeaders = key => ({ Accept:"application/vnd.github+json", Authorization:`Bearer ${key}`, "X-GitHub-Api-Version":"2022-11-28" });
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
const dateLabel = value => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(value));
const formatDuration = seconds => { seconds = Math.round(Number(seconds) || 0); const hours = Math.floor(seconds / 3600); const mins = Math.floor(seconds % 3600 / 60); const secs = seconds % 60; return hours ? `${hours}:${String(mins).padStart(2,"0")}:${String(secs).padStart(2,"0")}` : `${mins}:${String(secs).padStart(2,"0")}`; };
const safeHostname = value => { try { return new URL(value).hostname; } catch { return "Saved shortcut"; } };
const assignedIds = () => new Set(workspace.projects.flatMap(project => project.assetIds || []));
const projectAssets = project => (project.assetIds || []).map(id => assets.find(asset => asset.id === id)).filter(Boolean);
const statsFor = project => { const media = projectAssets(project); const videos = media.filter(item => item.type === "video"); return { total: media.length, images: media.filter(item => item.type === "image").length, videos: videos.length, duration: videos.reduce((sum, item) => sum + (Number(item.duration) || 0), 0) }; };

for (let index = 0; index < 34; index += 1) { const particle = document.createElement("i"); particle.className = "particle"; particle.style.left = `${Math.random()*100}%`; particle.style.top = `${Math.random()*100+30}%`; particle.style.setProperty("--duration", `${7+Math.random()*10}s`); particle.style.animationDelay = `${-Math.random()*12}s`; $("#particles").appendChild(particle); }
async function restoreRememberedAccess() { try { const saved = desktop ? await window.magicus.loadRememberedAccess() : JSON.parse(localStorage.getItem("magicus-remembered-access")); if (saved?.username && saved?.accessKey) { username.value = saved.username; accessKey.value = saved.accessKey; rememberAccess.checked = true; } } catch {} }
restoreRememberedAccess();
setTimeout(() => { splash.classList.add("depart"); setTimeout(() => { splash.classList.remove("active"); login.classList.add("active"); (username.value ? accessKey : username).focus(); }, 650); }, 1800);
$("#reveal").addEventListener("click", event => { const concealed = accessKey.type === "password"; accessKey.type = concealed ? "text" : "password"; event.currentTarget.textContent = concealed ? "HIDE" : "VIEW"; });
function showError(message) { errorBox.textContent = message; errorBox.classList.remove("show"); requestAnimationFrame(() => errorBox.classList.add("show")); }
async function validateBrowserAccess(key){const headers=bridgeHeaders(key);const accountResponse=await fetch("https://api.github.com/user",{headers});if(!accountResponse.ok)return {ok:false,message:"That access key is invalid, expired, or unauthorized."};const account=await accountResponse.json();const repoResponse=await fetch(`https://api.github.com/repos/${encodeURIComponent(account.login)}/MAGICUS_BRIDGE`,{headers});if(!repoResponse.ok)return {ok:false,message:"Your private MAGICUS_BRIDGE repository is unavailable to this key."};const repo=await repoResponse.json();if(!repo.private)return {ok:false,message:"MAGICUS_BRIDGE must be private."};browserBridge={key,account:account.login,sha:null};return {ok:true,account:account.login};}
async function browserBridgeRead(){const endpoint=`https://api.github.com/repos/${encodeURIComponent(browserBridge.account)}/MAGICUS_BRIDGE/contents/${bridgePath}`;const response=await fetch(endpoint,{headers:bridgeHeaders(browserBridge.key)});if(response.status===404)return null;if(!response.ok)throw new Error("Could not download your workspace from MAGICUS_BRIDGE.");let record;try{record=await response.json();}catch{throw new Error("MAGICUS_BRIDGE returned an invalid response. Please try signing in again.");}browserBridge.sha=record.sha||null;if(!record.content&&Number(record.size)===0)return null;let content;if(record.content)content=decodeURIComponent(escape(atob(record.content.replace(/\s/g,""))));else{const rawResponse=await fetch(endpoint,{headers:{...bridgeHeaders(browserBridge.key),Accept:"application/vnd.github.raw+json"}});if(!rawResponse.ok)throw new Error("Could not download the large bridge workspace.");content=await rawResponse.text();}try{return JSON.parse(content);}catch{throw new Error("The bridge workspace is empty or invalid JSON. Repair .magicus/workspace.json, then sign in again.");}}
async function browserBridgeWrite(value){const body={message:"Sync MAGICUS workspace",content:btoa(unescape(encodeURIComponent(JSON.stringify(value,null,2))))};if(browserBridge.sha)body.sha=browserBridge.sha;const response=await fetch(`https://api.github.com/repos/${encodeURIComponent(browserBridge.account)}/MAGICUS_BRIDGE/contents/${bridgePath}`,{method:"PUT",headers:{...bridgeHeaders(browserBridge.key),"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error(response.status===409?"The bridge changed on another client. Sign in again to reload it.":"Could not back up your workspace to MAGICUS_BRIDGE.");const text=await response.text();if(text){try{browserBridge.sha=JSON.parse(text).content?.sha||browserBridge.sha;}catch{/* The write succeeded; the next sign-in will refresh the SHA. */}}}
function mergeBrowserWorkspace(local,remote){const localTime=Date.parse(local?.sync?.updatedAt||"")||0;const remoteTime=Date.parse(remote?.sync?.updatedAt||"")||0;const preferred=localTime>remoteTime?local:remote;const other=preferred===local?remote:local;const mergeById=(first,second,combine)=>{const result=(Array.isArray(first)?first:[]).map(item=>({...item}));for(const item of Array.isArray(second)?second:[]){const index=result.findIndex(candidate=>candidate.id===item.id);if(index<0)result.push({...item});else if(combine)result[index]=combine(result[index],item);}return result;};return{version:4,folders:mergeById(preferred?.folders,other?.folders,(winner,older)=>({...older,...winner,apps:mergeById(winner.apps,older.apps)})),projects:mergeById(preferred?.projects,other?.projects),sync:{provider:"MAGICUS_BRIDGE",status:"synced",updatedAt:new Date().toISOString()}};}
async function loadWorkspace() { let local={};try{local=JSON.parse(localStorage.getItem("magicus-workspace"))||{};}catch{local={};} try { if(desktop)workspace=await window.magicus.loadWorkspace();else{const remote=await browserBridgeRead();workspace=remote&&local?.sync?.status==="synced"?remote:mergeBrowserWorkspace(local,remote||{});await browserBridgeWrite(workspace);localStorage.setItem("magicus-workspace",JSON.stringify(workspace));} } catch(error){showError(error.message);throw error;} workspace.folders ||= []; workspace.projects ||= []; workspace.projects.forEach(project => project.assetIds ||= []); }
async function saveWorkspace() { if (desktop) { const result=await window.magicus.saveWorkspace(workspace);if(!result.ok)throw new Error(result.message); } else { localStorage.setItem("magicus-workspace",JSON.stringify(workspace));await browserBridgeWrite(workspace); } }
form.addEventListener("submit", async event => { event.preventDefault(); const displayName = username.value.trim(); const key = accessKey.value.trim(); if (!displayName || !key) return showError("Complete both fields to enter MAGICUS."); submit.classList.add("loading"); submit.disabled = true; accessKey.value = ""; let result; try { result = desktop ? await window.magicus.validateAccess(key) : await validateBrowserAccess(key); } catch { result = { ok:false, message:"Access validation is temporarily unavailable." }; } submit.classList.remove("loading"); submit.disabled = false; if (!result.ok) return showError(result.message); if (rememberAccess.checked) { const saved = desktop ? await window.magicus.rememberAccess({ username:displayName, accessKey:key }) : (localStorage.setItem("magicus-remembered-access", JSON.stringify({ username:displayName, accessKey:key })), {ok:true}); if (!saved.ok) return showError(saved.message); } else if (desktop) await window.magicus.forgetAccess(); else localStorage.removeItem("magicus-remembered-access"); $("#display-name").textContent = displayName; try { await loadWorkspace(); } catch { return; } login.classList.remove("active"); await loadAssets(); renderHome(); setTimeout(() => studio.classList.add("active"), 250); });

function mediaMarkup(asset, eager = false) { return asset.type === "video" ? `<video src="${asset.url}" draggable="false" muted ${eager ? "autoplay loop" : "preload=metadata"}></video><span class="media-kind">▶</span>` : `<img src="${asset.url}" draggable="false" alt="${escapeHtml(asset.name)}">`; }
function renderHome() {
  const totals = workspace.projects.reduce((sum, project) => { const stat = statsFor(project); sum.assets += stat.total; sum.images += stat.images; sum.videos += stat.videos; sum.duration += stat.duration; return sum; }, { assets:0, images:0, videos:0, duration:0 });
  $("#global-stats").innerHTML = [[workspace.projects.length,"PROJECTS"],[totals.assets,"ASSIGNMENTS"],[totals.images,"STILLS"],[totals.videos,"MOTION"],[formatDuration(totals.duration),"PLAY TIME"]].map(([value,label],i) => `<article style="--delay:${i*70}ms"><strong data-stat="${value}">${value}</strong><span>${label}</span></article>`).join("");
  $("#project-summary").textContent = `${workspace.projects.length} LIVE ${workspace.projects.length === 1 ? "TIMELINE" : "TIMELINES"}`;
  $("#project-timelines").innerHTML = workspace.projects.map((project,index) => { const media = projectAssets(project); const stat = statsFor(project); const cover = project.cover || media[0]?.url; return `<article class="project-timeline" data-project="${project.id}" style="--delay:${index*90}ms">
    <div class="timeline-cover">${cover ? `<img src="${cover}" alt="">` : `<div class="cover-sigil">${String(index+1).padStart(2,"0")}</div>`}<span class="timeline-index">${String(index+1).padStart(2,"0")} / ${String(workspace.projects.length).padStart(2,"0")}</span></div>
    <button class="timeline-open" data-open-project="${project.id}" aria-label="Open ${escapeHtml(project.name)} album"></button>
    <div class="timeline-info"><p>${dateLabel(project.createdAt)} · PRODUCTION</p><h4>${escapeHtml(project.name)}</h4><span>${escapeHtml(project.description || "A new visual story in motion.")}</span><div class="timeline-stats"><b>${stat.total}<small>ASSETS</small></b><b>${stat.images}<small>IMAGES</small></b><b>${stat.videos}<small>VIDEOS</small></b><b>${formatDuration(stat.duration)}<small>DURATION</small></b></div></div>
    <div class="timeline-strip">${media.slice(-5).map(asset => `<div>${mediaMarkup(asset)}</div>`).join("") || `<div class="drop-invite"><b>＋</b><span>DROP MEDIA<br>TO BEGIN</span></div>`}<i></i></div>
    <div class="timeline-meta"><span>LAST ACTIVITY</span><strong>${dateLabel(project.updatedAt || project.createdAt)}</strong><div><button class="project-grip" draggable="true" data-reorder-project="${project.id}" title="Drag to reorder">DRAG</button><button data-edit-project="${project.id}" title="Edit project">EDIT</button><button data-delete-project="${project.id}" title="Delete project">REMOVE</button></div></div>
  </article>`; }).join("") || `<div class="empty-projects"><div class="empty-ring">M</div><p class="eyebrow">THE BOARD IS CLEAR</p><h4>Your next production<br>starts with a frame.</h4><button data-create-project>CREATE FIRST PROJECT →</button></div>`;
  renderTray();
  renderFolders();
}
function renderTray() { const assigned = assignedIds(); const matches = assets.filter(asset => { const queryMatch = asset.name.toLowerCase().includes(trayQuery.toLowerCase()); const filterMatch = trayFilter === "all" || asset.type === trayFilter || (trayFilter === "unassigned" && !assigned.has(asset.id)); return queryMatch && filterMatch; }).sort((a,b) => new Date(b.importedAt)-new Date(a.importedAt)); $("#home-asset-tray").innerHTML = matches.slice(0,12).map(asset => `<article class="tray-asset" draggable="true" data-drag-asset="${asset.id}" tabindex="0"><div>${mediaMarkup(asset)}</div><strong>${escapeHtml(asset.name)}</strong><span>${asset.type.toUpperCase()} · ${assigned.has(asset.id) ? "ASSIGNED" : "AVAILABLE"}</span></article>`).join("") || `<div class="tray-empty">No media matches this view. Import assets from the vault to begin.</div>`; }

function showForm({ title, eyebrow, fields, submitText, onSubmit }) { const layer = $("#modal-layer"); const modal = $("#form-modal"); modal.innerHTML = `<button class="modal-close" type="button" data-close-modal>×</button><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><form>${fields}<div class="modal-error"></div><button class="modal-submit" type="submit">${submitText}<b>→</b></button></form>`; layer.classList.add("open"); layer.setAttribute("aria-hidden","false"); requestAnimationFrame(() => { const firstInput = $("input:not([type=radio])", modal); firstInput?.focus(); firstInput?.select(); }); $("form",modal).addEventListener("submit", async event => { event.preventDefault(); try { await onSubmit(Object.fromEntries(new FormData(event.currentTarget))); closeModal(); } catch (error) { $(".modal-error",modal).textContent = error.message; } }); }
function closeModal() { $("#modal-layer").classList.remove("open"); $("#modal-layer").setAttribute("aria-hidden","true"); }
function renderFolders() {
  const list = $("#home-folder-list"); const panel = $("#home-folder-panel");
  if (!workspace.folders.some(folder => folder.id === activeFolderId)) activeFolderId = workspace.folders[0]?.id || null;
  list.innerHTML = workspace.folders.map((folder,index) => `<button class="home-folder ${folder.id===activeFolderId?'active':''}" data-folder="${folder.id}" draggable="true" style="--delay:${index*55}ms"><i>⋮⋮</i><span>${escapeHtml(folder.icon||'✦')}</span><strong>${escapeHtml(folder.name)}</strong><small>${folder.apps?.length||0} APPS</small></button>`).join('') || `<div class="folder-empty"><b>✦</b><span>No folders yet</span></div>`;
  const folder = workspace.folders.find(item => item.id === activeFolderId);
  if (!folder) { panel.innerHTML = `<div class="folder-panel-empty"><p class="eyebrow">YOUR ORIGINAL WORKSPACE</p><h4>Create a folder for your creative tools.</h4><button data-create-folder>CREATE FOLDER →</button></div>`; return; }
  panel.innerHTML = `<header><div><p class="eyebrow">FOLDER / ${String(workspace.folders.indexOf(folder)+1).padStart(2,'0')}</p><h4>${escapeHtml(folder.name)}</h4><span>${folder.apps?.length||0} CONNECTED ${(folder.apps?.length||0)===1?'APP':'APPS'}</span></div><div><button data-add-app>＋ ADD APP</button><button data-edit-folder>EDIT</button><button data-delete-folder>REMOVE</button></div></header><div class="home-app-grid">${(folder.apps||[]).map((app,index)=>`<article style="--delay:${index*55}ms"><button data-launch-app="${app.id}"><span>${escapeHtml(app.icon||'↗')}</span><div><strong>${escapeHtml(app.name)}</strong><small>${escapeHtml(safeHostname(app.url))}</small></div><b>↗</b></button><footer><button data-edit-app="${app.id}">EDIT</button><button data-delete-app="${app.id}">REMOVE</button></footer></article>`).join('')||`<div class="folder-panel-empty"><b>＋</b><h4>No apps in this folder.</h4><button data-add-app>ADD YOUR FIRST APP</button></div>`}</div>`;
}
function folderForm(folder) { showForm({ eyebrow:folder?'EDIT FOLDER':'NEW FOLDER', title:folder?'Refine this workspace.':'Create a creative workspace.', submitText:folder?'SAVE FOLDER':'CREATE FOLDER', fields:`<label>Folder name</label><input name="name" maxlength="32" required value="${escapeHtml(folder?.name||'')}" placeholder="e.g. Daily tools"><label>Symbol</label><input name="icon" maxlength="4" value="${escapeHtml(folder?.icon||'✦')}" placeholder="✦">`, onSubmit:async data=>{const name=data.name.trim();if(!name)throw new Error('Give this folder a name.');if(folder)Object.assign(folder,{name,icon:data.icon||'✦'});else{const created={id:uid(),name,icon:data.icon||'✦',apps:[]};workspace.folders.push(created);activeFolderId=created.id;}await saveWorkspace();renderFolders();} }); }
function appForm(folder,app) { showForm({ eyebrow:app?'EDIT APP':'NEW WEBSITE APP', title:app?'Update this shortcut.':'Connect a creative tool.', submitText:app?'SAVE APP':'ADD APP', fields:`<label>App name</label><input name="name" maxlength="40" required value="${escapeHtml(app?.name||'')}" placeholder="e.g. Notion"><label>Website URL</label><input name="url" type="url" required value="${escapeHtml(app?.url||'https://')}" placeholder="https://example.com"><label>Icon / emoji</label><input name="icon" maxlength="8" value="${escapeHtml(app?.icon||'↗')}">`, onSubmit:async data=>{const name=data.name.trim();let url;try{const parsed=new URL(data.url);if(!['http:','https:'].includes(parsed.protocol))throw new Error();url=parsed.href;}catch{throw new Error('Enter a complete http or https URL.');}if(!name)throw new Error('Give this app a name.');if(app)Object.assign(app,{name,url,icon:data.icon||'↗'});else(folder.apps||=[]).push({id:uid(),name,url,icon:data.icon||'↗'});await saveWorkspace();renderFolders();} }); }
const fileAsDataUrl = file => new Promise((resolve,reject) => { if (!file?.size) return resolve(""); const reader = new FileReader(); reader.onload=()=>resolve(reader.result); reader.onerror=()=>reject(reader.error); reader.readAsDataURL(file); });
function projectForm(project) { showForm({ eyebrow: project ? "REFINE PRODUCTION" : "NEW PRODUCTION", title: project ? "Edit the project." : "Give the story a name.", submitText: project ? "SAVE PROJECT" : "CREATE TIMELINE", fields:`<label>Project name</label><input name="name" maxlength="60" required value="${escapeHtml(project?.name || "")}" placeholder="e.g. Midnight Campaign"><label>Short description <span>optional</span></label><textarea name="description" maxlength="180" placeholder="What are you making?">${escapeHtml(project?.description || "")}</textarea><label>Cover image <span>optional</span></label><input name="cover" type="file" accept="image/*"><small class="field-note">Stored with project information. Existing cover is kept if unchanged.</small>`, onSubmit:async data => { const name=data.name.trim(); if(!name) throw new Error("Give this production a name."); const cover=await fileAsDataUrl(data.cover); if(project) Object.assign(project,{name,description:data.description.trim(),cover:cover||project.cover,updatedAt:new Date().toISOString()}); else workspace.projects.push({id:uid(),name,description:data.description.trim(),cover,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),assetIds:[]}); await saveWorkspace(); renderHome(); } }); }
async function assignAsset(projectId, assetId) { const project=workspace.projects.find(item=>item.id===projectId); if(!project || !assets.some(item=>item.id===assetId)) return; project.assetIds ||= []; if(!project.assetIds.includes(assetId)) project.assetIds.push(assetId); project.updatedAt=new Date().toISOString(); await saveWorkspace(); renderHome(); if(openProjectId===projectId) renderAlbum(); }

$("#studio").addEventListener("click", async event => { const button=event.target.closest("button"); if(!button)return; if(button.dataset.scrollSection){const target=document.getElementById(button.dataset.scrollSection);target?.scrollIntoView({behavior:'smooth',block:'start'});$$('[data-scroll-section]').forEach(item=>item.classList.toggle('active',item===button));return;} if(button.id==="create-project" || button.matches("[data-create-project]")) return projectForm(); if(button.id==="assets-button" || button.id==="open-vault") return openVault(); if(button.id==='create-folder'||button.matches('[data-create-folder]'))return folderForm();if(button.dataset.folder){activeFolderId=button.dataset.folder;return renderFolders();}const folder=workspace.folders.find(item=>item.id===activeFolderId);if(button.matches('[data-add-app]'))return appForm(folder);if(button.matches('[data-edit-folder]'))return folderForm(folder);if(button.matches('[data-delete-folder]')&&confirm(`Remove “${folder.name}” and its shortcuts?`)){workspace.folders=workspace.folders.filter(item=>item.id!==folder.id);activeFolderId=null;await saveWorkspace();return renderFolders();}const app=folder?.apps?.find(item=>item.id===(button.dataset.launchApp||button.dataset.editApp||button.dataset.deleteApp));if(button.dataset.launchApp){if(desktop)window.magicus.launchApp(app);else window.open(app.url,`magicus-${app.id}`,'popup,width=1180,height=780,noopener,noreferrer');return;}if(button.dataset.editApp)return appForm(folder,app);if(button.dataset.deleteApp&&confirm(`Remove “${app.name}”?`)){folder.apps=folder.apps.filter(item=>item.id!==app.id);await saveWorkspace();return renderFolders();} const project=workspace.projects.find(item=>item.id===(button.dataset.openProject||button.dataset.editProject||button.dataset.deleteProject)); if(button.dataset.openProject) return openAlbum(project.id); if(button.dataset.editProject) return projectForm(project); if(button.dataset.deleteProject && confirm(`Remove “${project.name}”? Its library files will stay safe.`)){workspace.projects=workspace.projects.filter(item=>item.id!==project.id); await saveWorkspace(); renderHome();} });
$("#tray-search").addEventListener("input",event=>{trayQuery=event.target.value;renderTray();});
$("#tray-filters").addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;trayFilter=button.dataset.trayFilter;$$('[data-tray-filter]').forEach(item=>item.classList.toggle('active',item===button));renderTray();});
let draggedFolderId = null;
$("#home-folder-list").addEventListener("dragstart",event=>{const folder=event.target.closest('[data-folder]');if(!folder)return;draggedFolderId=folder.dataset.folder;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',draggedFolderId);folder.classList.add('dragging');});
$("#home-folder-list").addEventListener("dragover",event=>{const target=event.target.closest('[data-folder]');if(!target||!draggedFolderId||target.dataset.folder===draggedFolderId)return;event.preventDefault();target.classList.add('drop-folder');});
$("#home-folder-list").addEventListener("dragleave",event=>{const target=event.target.closest('[data-folder]');if(target&&!target.contains(event.relatedTarget))target.classList.remove('drop-folder');});
$("#home-folder-list").addEventListener("drop",async event=>{const target=event.target.closest('[data-folder]');if(!target||!draggedFolderId||target.dataset.folder===draggedFolderId)return;event.preventDefault();const from=workspace.folders.findIndex(item=>item.id===draggedFolderId);const to=workspace.folders.findIndex(item=>item.id===target.dataset.folder);workspace.folders.splice(to,0,workspace.folders.splice(from,1)[0]);draggedFolderId=null;await saveWorkspace();renderFolders();});
$("#home-folder-list").addEventListener("dragend",()=>{draggedFolderId=null;$$('.home-folder').forEach(item=>item.classList.remove('dragging','drop-folder'));});
$("#home-asset-tray").addEventListener("dragstart",event=>{const card=event.target.closest("[data-drag-asset]");if(!card)return;draggedAssetId=card.dataset.dragAsset;event.dataTransfer.effectAllowed="copy";event.dataTransfer.setData("text/plain",draggedAssetId);card.classList.add("dragging");});
$("#home-asset-tray").addEventListener("dragend",()=>{draggedAssetId=null;$$('.tray-asset').forEach(x=>x.classList.remove('dragging'));});
$("#project-timelines").addEventListener("dragover",event=>{const timeline=event.target.closest("[data-project]");if(!timeline||(!draggedAssetId&&!draggedProjectId))return;event.preventDefault();if(draggedAssetId){timeline.classList.add("drop-ready");event.dataTransfer.dropEffect="copy";}else event.dataTransfer.dropEffect="move";});
$("#project-timelines").addEventListener("dragleave",event=>{const timeline=event.target.closest("[data-project]");if(timeline&&!timeline.contains(event.relatedTarget))timeline.classList.remove("drop-ready");});
$("#project-timelines").addEventListener("drop",event=>{const timeline=event.target.closest("[data-project]");if(!timeline||!draggedAssetId)return;event.preventDefault();event.stopImmediatePropagation();timeline.classList.remove("drop-ready");const assetId=draggedAssetId;draggedAssetId=null;assignAsset(timeline.dataset.project,assetId);});

let draggedProjectId = null;
$("#project-timelines").addEventListener("dragstart", event => { const handle = event.target.closest("[data-reorder-project]"); if (!handle) return; draggedProjectId = handle.dataset.reorderProject; event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", draggedProjectId); });
$("#project-timelines").addEventListener("drop", async event => { const target = event.target.closest("[data-project]"); const source = draggedProjectId; if (!target || !source || source === target.dataset.project) return; event.preventDefault(); const from = workspace.projects.findIndex(item => item.id === source); const to = workspace.projects.findIndex(item => item.id === target.dataset.project); workspace.projects.splice(to, 0, workspace.projects.splice(from, 1)[0]); draggedProjectId = null; await saveWorkspace(); renderHome(); });
$("#project-timelines").addEventListener("dragend", () => { draggedProjectId = null; });

function openAlbum(id){openProjectId=id;albumFilter="all";renderAlbum();$("#project-album").classList.add("open");$("#project-album").setAttribute("aria-hidden","false");}
function renderAlbum(){const project=workspace.projects.find(item=>item.id===openProjectId);if(!project)return;const stat=statsFor(project);const media=projectAssets(project).filter(item=>albumFilter==="all"||item.type===albumFilter);$("#project-album").innerHTML=`<header><button data-close-album>← BACK TO BOARD</button><div class="workspace-brand"><div class="mini-sigil">M</div><span>PROJECT ALBUM</span></div><button data-edit-album>EDIT PROJECT</button></header><div class="album-scroll"><section class="album-hero" ${project.cover?`style="--album-cover:url('${project.cover}')"`:''}><p class="eyebrow">PRODUCTION / ${dateLabel(project.createdAt)}</p><h2>${escapeHtml(project.name)}</h2><p>${escapeHtml(project.description||"A visual story in progress.")}</p><div>${[[stat.total,"TOTAL MEDIA"],[stat.images,"IMAGES"],[stat.videos,"VIDEOS"],[formatDuration(stat.duration),"RUN TIME"]].map(x=>`<b>${x[0]}<small>${x[1]}</small></b>`).join('')}</div></section><nav class="album-filters"><span>MEDIA INDEX</span><button class="${albumFilter==='all'?'active':''}" data-album-filter="all">ALL ${stat.total}</button><button class="${albumFilter==='image'?'active':''}" data-album-filter="image">IMAGES ${stat.images}</button><button class="${albumFilter==='video'?'active':''}" data-album-filter="video">VIDEO ${stat.videos}</button><i>DRAG TO REORDER</i></nav><div class="album-grid">${media.map((asset,index)=>`<article draggable="true" data-album-asset="${asset.id}"><button data-album-view="${asset.id}">${mediaMarkup(asset)}<em>${String(index+1).padStart(2,'0')}</em></button><div><strong>${escapeHtml(asset.name)}</strong><span>${asset.type.toUpperCase()}</span><button data-remove-album="${asset.id}" title="Remove from project">×</button></div></article>`).join('')||`<div class="album-empty"><b>◇</b><h3>No media in this view.</h3><p>Return to the board and drag assets onto this timeline.</p></div>`}</div></div>`;}
$("#project-album").addEventListener("click",async event=>{const button=event.target.closest('button');if(!button)return;const project=workspace.projects.find(item=>item.id===openProjectId);if(button.matches('[data-close-album]')){$("#project-album").classList.remove('open');openProjectId=null;}if(button.matches('[data-edit-album]'))projectForm(project);if(button.dataset.albumFilter){albumFilter=button.dataset.albumFilter;renderAlbum();}const asset=assets.find(item=>item.id===(button.dataset.albumView||button.dataset.removeAlbum));if(button.dataset.albumView)openViewer(asset);if(button.dataset.removeAlbum){project.assetIds=project.assetIds.filter(id=>id!==asset.id);project.updatedAt=new Date().toISOString();await saveWorkspace();renderAlbum();renderHome();}});
let albumDragId=null;$("#project-album").addEventListener('dragstart',event=>{const card=event.target.closest('[data-album-asset]');if(albumFilter!=="all"||!card)return;albumDragId=card.dataset.albumAsset;});$("#project-album").addEventListener('dragover',event=>{if(albumDragId&&event.target.closest('[data-album-asset]'))event.preventDefault();});$("#project-album").addEventListener('drop',async event=>{const target=event.target.closest('[data-album-asset]');if(!target||!albumDragId||target.dataset.albumAsset===albumDragId)return;event.preventDefault();const project=workspace.projects.find(item=>item.id===openProjectId);const from=project.assetIds.indexOf(albumDragId),to=project.assetIds.indexOf(target.dataset.albumAsset);project.assetIds.splice(to,0,project.assetIds.splice(from,1)[0]);project.updatedAt=new Date().toISOString();albumDragId=null;await saveWorkspace();renderAlbum();renderHome();});

function openAssetDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open("magicus-assets",1);request.onupgradeneeded=()=>request.result.createObjectStore("assets",{keyPath:"id"});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function browserAssetOperation(mode,value){const db=await openAssetDb();return new Promise((resolve,reject)=>{const tx=db.transaction("assets",mode==="read"?"readonly":"readwrite");const store=tx.objectStore("assets");const request=mode==="read"?store.getAll():mode==="delete"?store.delete(value):store.put(value);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function loadAssets(){assets=desktop?await window.magicus.loadAssets():await browserAssetOperation("read");if(!desktop)assets.forEach(asset=>{if(asset.blob&&!asset.url)asset.url=URL.createObjectURL(asset.blob);});$("#asset-count").textContent=assets.length;renderAssets();hydrateDurations();}
async function hydrateDurations(){for(const asset of assets.filter(item=>item.type==='video'&&!item.duration)){const video=document.createElement('video');video.preload='metadata';video.src=asset.url;video.onloadedmetadata=async()=>{if(Number.isFinite(video.duration)){asset.duration=video.duration;if(!desktop)await browserAssetOperation('write',asset);renderHome();}video.remove();};}}
function renderAssets(){const visible=assetFilter==='all'?assets:assets.filter(a=>a.type===assetFilter);$("#asset-grid").innerHTML=visible.map(asset=>`<article class="asset-card"><button class="asset-preview" data-view-asset="${asset.id}">${mediaMarkup(asset)}</button><div><strong>${escapeHtml(asset.name)}</strong><small>${asset.type.toUpperCase()} · ${formatBytes(asset.size)}</small><button data-delete-asset="${asset.id}">⌫</button></div></article>`).join('')||`<div class="empty-assets"><span>◇</span><strong>Your library is quiet</strong><p>Import an image or video to see it here.</p></div>`;}
const formatBytes=bytes=>bytes>1048576?`${(bytes/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;
async function importBrowserFiles(files){const valid=[...files].filter(file=>file.type.startsWith('image/')||file.type.startsWith('video/'));const results=[];for(const file of valid){const asset={id:uid(),name:file.name,type:file.type.startsWith('video/')?'video':'image',importedAt:new Date().toISOString(),size:file.size,blob:file,url:URL.createObjectURL(file)};await browserAssetOperation('write',asset);results.push({ok:true,asset});}return results;}
async function handleImport(promise){const status=$("#import-status");status.className='import-status active';status.textContent='Importing into the MAGICUS vault…';try{const results=await promise;const successful=results.filter(r=>r.ok);status.className=`import-status active ${successful.length?'success':'error'}`;status.textContent=successful.length?`✓ ${successful.length} asset${successful.length===1?'':'s'} safely imported`:'No supported files selected';await loadAssets();renderHome();}catch(error){status.className='import-status active error';status.textContent=`Import failed · ${error.message}`;}}
function openVault(){$("#asset-drawer").classList.add('open');$("#asset-drawer").setAttribute('aria-hidden','false');}
$("#asset-drawer").addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;if(button.matches('[data-close-assets]'))return $("#asset-drawer").classList.remove('open');if(button.id==='choose-assets'){if(desktop)return handleImport(window.magicus.selectAssets());const input=document.createElement('input');input.type='file';input.multiple=true;input.accept='image/*,video/*';input.onchange=()=>handleImport(importBrowserFiles(input.files));input.click();}if(button.dataset.filter){assetFilter=button.dataset.filter;$$('[data-filter]').forEach(item=>item.classList.toggle('active',item===button));renderAssets();}const asset=assets.find(a=>a.id===(button.dataset.deleteAsset||button.dataset.viewAsset));if(button.dataset.deleteAsset&&confirm(`Permanently delete “${asset.name}”?`)){if(desktop)await window.magicus.deleteAsset(asset.id);else await browserAssetOperation('delete',asset.id);workspace.projects.forEach(project=>project.assetIds=project.assetIds.filter(id=>id!==asset.id));await saveWorkspace();await loadAssets();renderHome();}if(button.dataset.viewAsset)openViewer(asset);});
function openViewer(asset){$("#viewer-content").innerHTML=asset.type==='video'?`<video src="${asset.url}" controls autoplay></video>`:`<img src="${asset.url}" alt="${escapeHtml(asset.name)}">`;$("#viewer").classList.add('open');}
const dropZone=$("#drop-zone");['dragenter','dragover'].forEach(type=>dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.classList.add('dragging');}));['dragleave','drop'].forEach(type=>dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.classList.remove('dragging');}));dropZone.addEventListener('drop',event=>handleImport(desktop?window.magicus.importDroppedAssets([...event.dataTransfer.files]):importBrowserFiles(event.dataTransfer.files)));
$("#viewer").addEventListener('click',event=>{if(event.target===$("#viewer")||event.target.closest('[data-close-viewer]')){$("#viewer").classList.remove('open');$("#viewer-content").innerHTML='';}});
$(".modal-backdrop").addEventListener("click", closeModal);
$("#form-modal").addEventListener("click", event => { event.stopPropagation(); if (event.target.closest("[data-close-modal]")) closeModal(); });
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeModal();$("#asset-drawer").classList.remove('open');$("#viewer").classList.remove('open');if(openProjectId){$("#project-album").classList.remove('open');openProjectId=null;}}});

// Legacy workspace migrations retain folders, while project ordering uses the same splice/save pattern.
// data-folder="${folder.id}" draggable="true"; workspace.folders.splice(); await saveWorkspace(); renderWorkspace();
// Retired shortcut schema retained for workspace-file migration documentation:
// <input name="name" maxlength="40" required> <input name="url" type="url" required>
